In [3]:
import pandas as pd
import numpy as np

In [4]:
def hypothesis(X,thetas):
    return np.dot(X,thetas)

In [5]:
def loss_fun(y_act,y_pred):
    return np.mean((y_act-y_pred)**2)

In [6]:
def der_loss_fun(X, y, thetas):
    h = hypothesis(X,thetas)
    dif = (y-h).T
    f=np.dot(dif,X)
    f=-2*f/float(X.shape[0])
    return f

In [7]:
def gradient_descent(nthetas, alpha, grad_thetas):
    return (nthetas -alpha * grad_thetas)

# Task-1

In [10]:
df = pd.read_csv("Advertising.csv")
df = df.iloc[:, 1:]
df

TV  radio  newspaper  sales
0    230.1   37.8       69.2   22.1
1     44.5   39.3       45.1   10.4
2     17.2   45.9       69.3    9.3
3    151.5   41.3       58.5   18.5
4    180.8   10.8       58.4   12.9
..     ...    ...        ...    ...
195   38.2    3.7       13.8    7.6
196   94.2    4.9        8.1    9.7
197  177.0    9.3        6.4   12.8
198  283.6   42.0       66.2   25.5
199  232.1    8.6        8.7   13.4

[200 rows x 4 columns]

In [82]:
one = np.ones(200)
X = df.iloc[: , :-1]
X['One'] = one
X = np.array(X)
y = df.iloc[:,-1:]
y = np.array(y)
thetas = np.array([[100] , [50] , [75] , [1]])
print("X Shape : " , X.shape)
print("Y Shape : " , y.shape)
print("Thetas Shape : " , thetas.shape)
alpha = 0.0001

X Shape :  (200, 4)
Y Shape :  (200, 1)
Thetas Shape :  (4, 1)


In [83]:
X, y

(array([[230.1,  37.8,  69.2,   1. ],
        [ 44.5,  39.3,  45.1,   1. ],
        [ 17.2,  45.9,  69.3,   1. ],
        [151.5,  41.3,  58.5,   1. ],
        [180.8,  10.8,  58.4,   1. ],
        [  8.7,  48.9,  75. ,   1. ],
        [ 57.5,  32.8,  23.5,   1. ],
        [120.2,  19.6,  11.6,   1. ],
        [  8.6,   2.1,   1. ,   1. ],
        [199.8,   2.6,  21.2,   1. ],
        [ 66.1,   5.8,  24.2,   1. ],
        [214.7,  24. ,   4. ,   1. ],
        [ 23.8,  35.1,  65.9,   1. ],
        [ 97.5,   7.6,   7.2,   1. ],
        [204.1,  32.9,  46. ,   1. ],
        [195.4,  47.7,  52.9,   1. ],
        [ 67.8,  36.6, 114. ,   1. ],
        [281.4,  39.6,  55.8,   1. ],
        [ 69.2,  20.5,  18.3,   1. ],
        [147.3,  23.9,  19.1,   1. ],
        [218.4,  27.7,  53.4,   1. ],
        [237.4,   5.1,  23.5,   1. ],
        [ 13.2,  15.9,  49.6,   1. ],
        [228.3,  16.9,  26.2,   1. ],
        [ 62.3,  12.6,  18.3,   1. ],
        [262.9,   3.5,  19.5,   1. ],
        [142

In [84]:
y_pred = hypothesis(X, thetas)
y_pred

array([[30091. ],
       [ 9798.5],
       [ 9213.5],
       [21603.5],
       [23001. ],
       [ 8941. ],
       [ 9153.5],
       [13871. ],
       [ 1041. ],
       [21701. ],
       [ 8716. ],
       [22971. ],
       [ 9078.5],
       [10671. ],
       [25506. ],
       [25893.5],
       [17161. ],
       [34306. ],
       [ 9318.5],
       [17358.5],
       [27231. ],
       [25758.5],
       [ 5836. ],
       [25641. ],
       [ 8233.5],
       [27928.5],
       [16701. ],
       [26563.5],
       [27953.5],
       [10921. ],
       [33946. ],
       [15056. ],
       [12046. ],
       [27583.5],
       [10196. ],
       [29913.5],
       [29256. ],
       [13368.5],
       [ 8278.5],
       [27086. ],
       [23736. ],
       [22273.5],
       [30881. ],
       [23091. ],
       [ 7043.5],
       [20998.5],
       [12143.5],
       [27453.5],
       [27253.5],
       [10036. ],
       [22731. ],
       [10791. ],
       [26696. ],
       [24973.5],
       [28903.5],
       [26

In [85]:
MSE = loss_fun(y, y_pred)
MSE

408872809.05125

In [86]:
grad_thetas = der_loss_fun(X, y, thetas)
grad_thetas = grad_thetas.T
grad_thetas

array([[6825341.3416],
       [ 897131.0866],
       [1212073.7077],
       [  36291.955 ]])

In [87]:
nthetas = gradient_descent(thetas, alpha, grad_thetas)
nthetas

array([[-582.53413416],
       [ -39.71310866],
       [ -46.20737077],
       [  -2.6291955 ]])

In [88]:
for i in range(100):
    y_pred = hypothesis(X, nthetas)
    grad_thetas = der_loss_fun(X, y, nthetas)
    grad_thetas = grad_thetas.T
    nthetas = gradient_descent(nthetas, alpha, grad_thetas)
    print("Loss for ", i +1, "Loop : ", loss_fun(y, y_pred))

Loss for  1 Loop :  10245565150.43966
Loss for  2 Loop :  258935092657.69727
Loss for  3 Loop :  6545610952253.798
Loss for  4 Loop :  165467377974489.84
Loss for  5 Loop :  4182872848598497.5
Loss for  6 Loop :  1.0573942473738133e+17
Loss for  7 Loop :  2.6730016307310413e+18
Loss for  8 Loop :  6.757118015031614e+19
Loss for  9 Loop :  1.7081412650160958e+21
Loss for  10 Loop :  4.318034071271358e+22
Loss for  11 Loop :  1.0915618410801986e+24
Loss for  12 Loop :  2.759374366287891e+25
Loss for  13 Loop :  6.975460855055007e+26
Loss for  14 Loop :  1.7633364553524404e+28
Loss for  15 Loop :  4.457562760920101e+29
Loss for  16 Loop :  1.126833492679661e+31
Loss for  17 Loop :  2.8485380651433575e+32
Loss for  18 Loop :  7.200859010034219e+33
Loss for  19 Loop :  1.820315168573372e+35
Loss for  20 Loop :  4.601600042885104e+36
Loss for  21 Loop :  1.1632448776041003e+38
Loss for  22 Loop :  2.940582911729522e+39
Loss for  23 Loop :  7.433540458450756e+40
Loss for  24 Loop :  1.8791350

In [74]:
print(grad_thetas)

[[-4362.46562742]
 [11222.94696351]
 [18196.08239048]
 [  226.40975108]]


In [32]:
#original value of thetas
print(thetas)

[[100]
 [ 50]
 [ 75]
 [  1]]


In [33]:
# Therefore, the original thetas and final thetas show a linear relationship between features and outputs...

# Task-2

In [63]:
X = np.array([[1,2,3,4,5] , [1,1,1,1,1]]).T
y = np.array([[3],[5],[7],[9],[11]])
nthetas = np.array([[10] , [1]])
thetas = nthetas
alpha = 0.066

In [64]:
for i in range(100):
    y_pred = hypothesis(X , nthetas)
    grad_thetas = der_loss_fun(X, y, nthetas)
    grad_thetas = grad_thetas.T
    nthetas = gradient_descent (nthetas, alpha, grad_thetas)
    print("Loss for ", i +1, "Loop : ", loss_fun(y, y_pred))

Loss for  1 Loop :  704.0
Loss for  2 Loop :  222.59916799999996
Loss for  3 Loop :  70.699863179264
Loss for  4 Loop :  22.756210163547394
Loss for  5 Loop :  7.610524733619438
Loss for  6 Loop :  2.81317377962013
Loss for  7 Loop :  1.2814665092507096
Loss for  8 Loop :  0.7808422984030051
Loss for  9 Loop :  0.6062824759014408
Loss for  10 Loop :  0.5353263014842767
Loss for  11 Loop :  0.49775710200823164
Loss for  12 Loop :  0.4713912304289316
Loss for  13 Loop :  0.4492003812462668
Loss for  14 Loop :  0.4289389242569266
Loss for  15 Loop :  0.40987136651012557
Loss for  16 Loop :  0.39173984171544424
Loss for  17 Loop :  0.3744383100645754
Loss for  18 Loop :  0.3579097209874419
Loss for  19 Loop :  0.3421135208756017
Loss for  20 Loop :  0.3270153561151292
Loss for  21 Loop :  0.3125837805627321
Loss for  22 Loop :  0.29878917479754247
Loss for  23 Loop :  0.285603365020639
Loss for  24 Loop :  0.2729994644581434
Loss for  25 Loop :  0.2609517866551304
Loss for  26 Loop :  0.24

In [65]:
nthetas # updated new thetas

array([[2.05967886],
       [0.78454039]])

In [66]:
thetas  #original thetas

array([[10],
       [ 1]])

# Task-3

Question: Is linear regression good for classification? If yes, then why, and if no, then why?

Answer: Linear regression is not suitable because it only works for continous values whereas classification problems are concerned with discret values. 

# Task-4

Question: Why do we use mse (mean squared error) over squared error? What is the benefit of mse?

Answer: MSE calculates the average squared difference between the actual and predicted values. squared error will not show a mean of all errors rather just sum up all squared errors.

# Task-5

Question: Can you find a better estimator than mse?

Answer: Yes. we can consider RMSE...