# Create a numpy array of int, characters, float and find their shapes

In [8]:
import numpy as np
int_arr = np.random.randint(1,8,10)
print("Array : ", int_arr)
print("Shape : ", int_arr.shape[0])

Array :  [2 3 5 5 4 6 1 7 6 7]
Shape :  10


In [13]:
float_arr = np.random.random(8)
print("Array : ", float_arr)
print("Shape : ", float_arr.shape[0])

Array :  [0.9182076  0.91838215 0.31108926 0.08758577 0.09763383 0.1015869
 0.86294284 0.36543627]
Shape :  8


In [30]:
arr = np.random.randint(65, 91, 5)
char_arr = [0] * 5
for i in range(len(arr)):
    char_arr[i] = chr(arr[i])
    count+=1
char_arr = np.array(char_arr)
print("Array : ", char_arr)
print("Shape : ", char_arr.shape[0])

Array :  ['T' 'K' 'N' 'U' 'O']
Shape :  5


# Create a zeros, empty, identity , eye and a full array

In [33]:
zeros_arr = np.zeros(5)
zeros_arr

array([0., 0., 0., 0., 0.])

In [36]:
ident_arr = np.identity(5)
ident_arr

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [41]:
eye_arr = np.eye(5,4)
eye_arr

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])

In [43]:
empty_arr = np.empty(5)
empty_arr

array([1., 1., 1., 1., 1.])

In [45]:
full_arr = np.full(8,2)
full_arr

array([2, 2, 2, 2, 2, 2, 2, 2])

# Declare an array having the datatype of object, is it possible?

In [51]:
object_type_arr = np.array([2, 4.34, 'Q', 'Helipad', '0.0', 0.0], dtype=object)
object_type_arr

array([2, 4.34, 'Q', 'Helipad', '0.0', 0.0], dtype=object)

# Create an array having 5 equally spaced numbers ranging from 5 to 15

In [53]:
ran_arr = np.linspace(5, 15, 5)
ran_arr

array([ 5. ,  7.5, 10. , 12.5, 15. ])

# Create a numpy array ranging from 1 to 100.

In [54]:
arr = np.arange(1, 101)
arr

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

# Reshape the above array into (100,15). Is it possible?

In [55]:
# No. It is not posssible!!!

# Reshape the array into (100,10).

In [64]:
resha_arr = arr.reshape(10, 10)
resha_arr

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

# Flatten and ravel the reshaped array. What is the difference?

In [66]:
arr = resha_arr.flatten()
arr

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [67]:
ravel_arr = resha_arr.ravel()
ravel_arr

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

Flatten is deep copy and is faster than ravel process while ravel is shallow copy and is slower than flatten process...

# Take an array [[1 2 3] [4 5 6] [ 7 8 9]]. Sum it along 0 and 1 axis

In [75]:
arr = np.array([[1,2,3], [4,5,6], [7,8,9]])
r_sum = np.sum(arr, axis=1)
c_sum = np.sum(arr, axis=0)
print("Column sum : ", c_sum)
print("Row sum : ", r_sum)

Column sum :  [12 15 18]
Row sum :  [ 6 15 24]


# Find the number of bytes used by your array

In [77]:
print(arr.nbytes)

36


# Find the maximum and minimum values in a 1D array.

In [100]:
arr = np.array([(1,10,5,3,2,1,8,12,4)])
print("Max Value : ", np.max(arr))
print("Min Value : ", np.min(arr))

Max Value :  12
Min Value :  1


# Find the maximum and minimum values in 2D array

In [108]:
arr = np.array([[1,2,3] , [4,5,6] , [7,8,9]])
print("Column minimum : ", np.min(arr , axis=0))
print("Column maximum : ", np.max(arr , axis=0))
print("Row minimum : ", np.min(arr , axis=1))
print("Row maximum : ", np.max(arr , axis=1))

Column minimum :  [1 2 3]
Column maximum :  [7 8 9]
Row minimum :  [1 4 7]
Row maximum :  [3 6 9]


# Sort an array

In [112]:
arr = np.array([2,3,5,43,0,987,8,88])
sort_arr= np.sort(arr)
sort_arr

array([  0,   2,   3,   5,   8,  43,  88, 987])

# Is * and mul the same as dot product for numpy arrays and matrices? Check.

In [124]:
arr_1 = np.array([1,2,3])
arr_2 = np.array([6,2,8])

dot_arr = np.dot(arr_1, arr_2)
mul_arr = arr_1 * arr_2

print("Dot Product : ", dot_arr)
print("mul : ", mul_arr)


Dot Product :  34
mul :  [ 6  4 24]


Both are Different...

# Take the square root and norm of an array.

In [130]:
arr = [1,4,9,25]
sqrt_arr = np.sqrt(arr)
norm_arr = np.linalg.norm(arr)
print("Square Root : ", sqrt_arr)
print("Normalized Array : ", norm_arr)

Square Root :  [1. 2. 3. 5.]
Normalized Array :  26.888659319497503


# Find the std, non-zero, zero values and mean of an array.

In [134]:
arr2 = np.array([12,30,60,3,0,2,0])
print("std : " , np.std(arr))
print("Non zero : ", arr2[arr2!=0])
print("Zero : ", arr2[arr2==0])
print("mean : ", np.mean(arr))

std :  9.256754290786809
Non zero :  [12 30 60  3  2]
Zero :  [0 0]
mean :  9.75


# Convert some angles to radians and vice versa.

In [137]:
angles_arr = np.random.uniform(0,360,5)

print("Array : ", angles_arr)
rad_arr = np.radians(angles_arr)
print("Radians Array : ", rad_arr)
angle_arr = np.degrees(rad_arr)
print("Angles Array : ", angle_arr)

Array :  [ 58.34086995 270.40938124 138.87739904  61.5592774   37.18908437]
Radians Array :  [1.01824027 4.71953403 2.42386787 1.07441208 0.64907197]
Angles Array :  [ 58.34086995 270.40938124 138.87739904  61.5592774   37.18908437]


# Save and load some of your arrays

In [142]:
arr = np.array([10,22,33,44])
np.save('Array_saved', arr)
np.load('Array_saved.npy')

array([10, 22, 33, 44])

# Calculate the mean, std, var, max, min, of an array with shape (3,3,12,3) containing floats drawn from a normal distribution with mean 21 and sigma 4.5. see the np.random.normal.

In [145]:
arr = np.random.normal(21, 4.5, [3,3,12,3])
arr

array([[[[17.3473004 , 17.94745932, 26.1243939 ],
         [ 6.94041622, 22.2037789 , 16.39548725],
         [24.27233199, 19.06087244, 23.74103735],
         [21.98038778, 22.28169427, 18.49601363],
         [20.64677339, 18.40579235, 16.79461376],
         [17.35076234, 26.97329773, 18.27847075],
         [23.21880128, 27.11102164, 24.34705952],
         [18.91103762, 17.20213491, 18.07051311],
         [25.28928248, 13.85861293, 18.44961325],
         [13.09374862, 14.44996255, 22.69675127],
         [17.59412522,  7.53350146, 18.39291537],
         [23.970992  , 14.96207291, 19.84871184]],

        [[20.33349315, 18.46664866, 25.42902807],
         [21.50201814, 20.81750327, 12.76425639],
         [17.17969716, 14.03395657, 22.3106445 ],
         [19.82956563, 21.3529292 , 16.7169448 ],
         [27.59035121, 25.7282752 ,  5.01826622],
         [20.51762126, 24.50924241, 22.21966341],
         [22.14407646, 27.57858004, 22.38181201],
         [14.64796729, 17.85398679, 20.18738271]

In [149]:
print("Mean : ", np.mean(arr))
print("Std : ", np.std(arr))
print("Var : ", np.var(arr))
print("Max : ", np.max(arr))
print("Min : ", np.min(arr))

Mean :  20.932393342955706
Std :  4.678350377049893
Var :  21.88696225044287
Max :  32.687966385795974
Min :  5.018266216658107
