# Question #1

In [2]:
balls= ['w', 'r', 'b']
combs=[]
for i in balls:
    for j in balls:
        for k in balls:
            combs.append(i+j+k)
combs

['www',
 'wwr',
 'wwb',
 'wrw',
 'wrr',
 'wrb',
 'wbw',
 'wbr',
 'wbb',
 'rww',
 'rwr',
 'rwb',
 'rrw',
 'rrr',
 'rrb',
 'rbw',
 'rbr',
 'rbb',
 'bww',
 'bwr',
 'bwb',
 'brw',
 'brr',
 'brb',
 'bbw',
 'bbr',
 'bbb']

In [3]:
w=6
r=4
b=5
prob_w = w/15
prob_r = r/15
prob_b = b/15

In [4]:
def combinations(n,r):
    n_fact=1
    n=n
    r=r

    for i in range(1,n+1):
        n_fact*=i

    nsubr = n - r
    nsubr_fact = 1
    for i in range(1,nsubr + 1):
        nsubr_fact*=i
    r_fact=1
    for i in range(1, r+1):
        r_fact*=i
    return (n_fact)/(nsubr_fact * r_fact)

In [5]:
combs_prob = []
prob=1
n_w=6
n_r=4
n_b=5
r_w=0
r_r=0
r_b=0

for i in combs:
    prob_w = 6/15
    prob_r = 4/15
    prob_b = 5/15
    
    for j in i:
        if(j=='w'):
            r_w+=1
        if(j=='r'):
            r_r+=1
        if(j=='b'):
            r_b+=1
    
    a=combinations(n_w,r_w)
    b=combinations(n_r,r_r)
    c=combinations(n_b,r_b)
    d=combinations(15,3)
    
    r_w=0
    r_r=0
    r_b=0
    
    combs_prob.append((a*b*c)/d)
    prob = 1
index = combs_prob.index(max(combs_prob))

In [6]:
print("Optimal Color Scheme : ", combs[index])
print("Optimal Color Scheme Probability : ", max(combs_prob))

Optimal Color Scheme :  wrb
Optimal Color Scheme Probability :  0.26373626373626374


# Question #2

In [99]:
import pandas as pd
import numpy as np
from sklearn.naive_bayes import GaussianNB
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import accuracy_score
from sklearn.metrics import f1_score

In [47]:
from sklearn.datasets import load_iris
iris = load_iris()

X = iris.data
y = iris.target

In [48]:
df = pd.DataFrame(iris.data, columns=iris.feature_names)
# Add a target column, and fill it with the target data
df['target'] = iris.target
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   target  
0       0  
1       0  
2       0  
3       0  
4       0

In [49]:
data =[]
for i in df["target"].unique():
    data.append(df[df["target"]==i])

for i in data:
    i.drop('target', inplace=True, axis=1)
data

C:\Users\QASIM KHAN\Downloads\New folder\lib\site-packages\pandas\core\frame.py:4308: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(


[    sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
 0                 5.1               3.5                1.4               0.2
 1                 4.9               3.0                1.4               0.2
 2                 4.7               3.2                1.3               0.2
 3                 4.6               3.1                1.5               0.2
 4                 5.0               3.6                1.4               0.2
 5                 5.4               3.9                1.7               0.4
 6                 4.6               3.4                1.4               0.3
 7                 5.0               3.4                1.5               0.2
 8                 4.4               2.9                1.4               0.2
 9                 4.9               3.1                1.5               0.1
 10                5.4               3.7                1.5               0.2
 11                4.8               3.4                1.6     

In [50]:
data = np.array(data)

In [51]:
data

array([[[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
        [5

In [52]:
Means_v = np.mean(data, axis =1)

In [53]:
Means_v

array([[5.006, 3.428, 1.462, 0.246],
       [5.936, 2.77 , 4.26 , 1.326],
       [6.588, 2.974, 5.552, 2.026]])

In [83]:
covarl=[]
for i in df['target'].unique():
    covarl.append(df[df['target']==i].cov())
for i in covarl:
    i.drop('target', inplace=True, axis=1)
covarl = np.array(covarl)

In [86]:
covarl

array([[[0.12424898, 0.09921633, 0.0163551 , 0.01033061],
        [0.09921633, 0.1436898 , 0.01169796, 0.00929796],
        [0.0163551 , 0.01169796, 0.03015918, 0.00606939],
        [0.01033061, 0.00929796, 0.00606939, 0.01110612],
        [0.        , 0.        , 0.        , 0.        ]],

       [[0.26643265, 0.08518367, 0.18289796, 0.05577959],
        [0.08518367, 0.09846939, 0.08265306, 0.04120408],
        [0.18289796, 0.08265306, 0.22081633, 0.07310204],
        [0.05577959, 0.04120408, 0.07310204, 0.03910612],
        [0.        , 0.        , 0.        , 0.        ]],

       [[0.40434286, 0.09376327, 0.3032898 , 0.04909388],
        [0.09376327, 0.10400408, 0.07137959, 0.04762857],
        [0.3032898 , 0.07137959, 0.30458776, 0.04882449],
        [0.04909388, 0.04762857, 0.04882449, 0.07543265],
        [0.        , 0.        , 0.        , 0.        ]]])

In [87]:
for i in range(3):
    for j in range(4):
        for k in range(4):
            if(j!=k):
                covarl[i][j][k] = 0          
covarl              

array([[[0.12424898, 0.        , 0.        , 0.        ],
        [0.        , 0.1436898 , 0.        , 0.        ],
        [0.        , 0.        , 0.03015918, 0.        ],
        [0.        , 0.        , 0.        , 0.01110612],
        [0.        , 0.        , 0.        , 0.        ]],

       [[0.26643265, 0.        , 0.        , 0.        ],
        [0.        , 0.09846939, 0.        , 0.        ],
        [0.        , 0.        , 0.22081633, 0.        ],
        [0.        , 0.        , 0.        , 0.03910612],
        [0.        , 0.        , 0.        , 0.        ]],

       [[0.40434286, 0.        , 0.        , 0.        ],
        [0.        , 0.10400408, 0.        , 0.        ],
        [0.        , 0.        , 0.30458776, 0.        ],
        [0.        , 0.        , 0.        , 0.07543265],
        [0.        , 0.        , 0.        , 0.        ]]])

In [88]:
def calculate_fx(x, covList, Means_v):
    temp=((2*3.142)**4)
    temp1=np.linalg.det(covList)
    temp2 = temp * temp1
    temp2= temp2**(1/2)
    temp5 = (x - Means_v).T
    temp3= (-0.5) * temp5
    temp4 = np.dot(np.linalg.inv(covList),  (x - Means_v))
    temp6 = (np.dot(temp3, temp4))
    temp5 = 2.71828**temp6

    fx=temp2 * temp5
    return fx

In [91]:
x=[6.7,3.0,5.2,2.3]
x = np.array(x)

p1 = calculate_fx(x,covarl[0][:4], Means_v[0])
p1 *= 1/3
p2 = calculate_fx(x,covarl[1][:4] , Means_v[1])
p2*=1/3
p3 = calculate_fx(x,covarl[2][:4],  Means_v[2])
p3*=1/3

In [92]:
print("Probability of flower being in class setosa = ", p1)
print("Probability of flower being in class versicolor = ", p2)
print("Probability of flower being in class virginica = ", p3)

Probability of flower being in class setosa =  1.3300505924970413e-190
Probability of flower being in class versicolor =  3.697114466351869e-08
Probability of flower being in class virginica =  0.19919796353149424


In [93]:
l=[]
if(p1>p2 and p1>p3):
    print("The flower belongs to class Setosa!")
    #l.append(0)
if(p1<p2 and p2>p3):
    print("The flower belongs to class Versicolor!")
    #l.append(1)
if(p3>p2 and p1<p3):
    print("The flower belongs to class Virginica!")
    #l.append(2)

The flower belongs to class Virginica!


## results with GaussianNB() built in function

In [106]:
iris = load_iris()

X = iris.data
y = iris.target
df = pd.DataFrame(iris.data, columns=iris.feature_names)
# Add a target column, and fill it with the target data
df['target'] = iris.target

labels = df['target']

le = LabelEncoder()

X = df.drop("target", axis = 1)

y = le.fit_transform(labels)

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state = 51)

clf = GaussianNB()
clf.fit(X_train, y_train)
pred = clf.predict(X_test)
re = clf.score(X_test,y_test)

x_test = np.array(X_test)
x_test[0]

n = 149*(0.3)

for i in range(0,int(n) +1):
    p1 = calculate_fx(x_test[i],covarl[0][:4], Means_v[0])
    p1 *= 1/3
    p2 = calculate_fx(x_test[i],covarl[1][:4] , Means_v[1])
    p2*=1/3
    p3 = calculate_fx(x_test[i],covarl[2][:4],  Means_v[2])
    p3*=1/3
    
    if(p1>p2 and p1>p3):
        print("The flower belongs to class Setosa!")
        l.append(0)
    if(p1<p2 and p2>p3):
        print("The flower belongs to class Versicolor!")
        l.append(1)
    if(p3>p2 and p1<p3):
        print("The flower belongs to class Virginica!")
        l.append(2)
        
count=0
for i in range(0,45):
    if l[i]==y_test[i]:
        count+=1
accur = count/len(y_test)

print("Accuracy of gauziian built in model : ", re*100)
print("Accuracy of my built model : ", accur*100)

The flower belongs to class Versicolor!
The flower belongs to class Virginica!
The flower belongs to class Versicolor!
The flower belongs to class Setosa!
The flower belongs to class Versicolor!
The flower belongs to class Virginica!
The flower belongs to class Virginica!
The flower belongs to class Virginica!
The flower belongs to class Setosa!
The flower belongs to class Virginica!
The flower belongs to class Virginica!
The flower belongs to class Setosa!
The flower belongs to class Versicolor!
The flower belongs to class Virginica!
The flower belongs to class Virginica!
The flower belongs to class Virginica!
The flower belongs to class Versicolor!
The flower belongs to class Virginica!
The flower belongs to class Virginica!
The flower belongs to class Setosa!
The flower belongs to class Virginica!
The flower belongs to class Virginica!
The flower belongs to class Setosa!
The flower belongs to class Setosa!
The flower belongs to class Versicolor!
The flower belongs to class Virginica

### The accuracy of gauziian model is very greater than my model. We can say that built in model is better than my own trained model.

# Bonus Task

In [109]:
pi = 3.142
r1 = 8
area_p1 = pi* (r1**2)

r2 = 5
#5 inch
area_p2 = pi* (r2**2)
area_p2 *= 2
print(area_p2, area_p1)

157.1 201.088


In [110]:
# I will take the deal as the pizza is more than 1 8 inch alone pizaa